version: "3"

services:
  db:
    image: mysql:8.0
    restart: always
    container_name: blog_db
    environment:
      MYSQL_DATABASE: blog
      MYSQL_USER: rp32
      MYSQL_PASSWORD: Strong@123
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql
    # Only set the authentication plugin, without a complex entrypoint.
    command: --default-authentication-plugin=mysql_native_password

  web:
    build: .
    container_name: blog_web
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
    command: python run.py
    environment:
      - DATABASE_URL=mysql+pymysql://rp32:Strong%40123@db:3306/blog

  ngrok:
    image: wernight/ngrok
    container_name: blog_ngrok
    restart: always
    depends_on:
      - web
    environment:
      - NGROK_AUTHTOKEN=2nIVWQ2YJzh3SU5Qe0vlaMXYImF_3m9YvqnfreUGd66PLf9QH
    command: ngrok http web:5000

volumes:
  db_data:
