services:
  - type: web
    name: blog-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn run:app"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blog-db
          property: connectionString

databases:
  - name: blog-db
    databaseName: blog
    user: bloguser
